#!/usr/bin/env python3
"""Script to create solution_v6.ipynb with all cells."""
import json

def make_code(src):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": src}

def make_md(src):
    return {"cell_type": "markdown", "metadata": {}, "source": src}

cells = []

cells.append(make_md(
    "# Vacancies 2026 — Salary Prediction v6\n"
    "**Key insight:** `MAPE(employer_id, experience) median` = **0.1165** on train\n\n"
    "**Pipeline:** Hierarchical lookup + LGB+XGB blend, alpha weighted by lookup confidence level"
))

cells.append(make_md("### 1. Imports & Config"))
cells.append(make_code(
    "import numpy as np\n"
    "import pandas as pd\n"
    "from sklearn.feature_extraction.text import TfidfVectorizer\n"
    "from sklearn.decomposition import TruncatedSVD\n"
    "from sklearn.model_selection import KFold\n"
    "from sklearn.preprocessing import OrdinalEncoder\n"
    "import lightgbm as lgb\n"
    "import xgboost as xgb\n"
    "import warnings\n"
    "warnings.filterwarnings('ignore')\n"
    "\n"
    "SEED     = 42\n"
    "N_SPLITS = 5\n"
    "STE_K    = 20\n"
    "np.random.seed(SEED)"
))

cells.append(make_md("### 2. Data Loading"))
cells.append(make_code(
    "train = pd.read_csv('data/train.csv')\n"
    "test  = pd.read_csv('data/test_x.csv')\n"
    "print(f'train: {train.shape}, test: {test.shape}')"
))

cells.append(make_md("### 3. Hierarchical Lookup Table"))
cells.append(make_code(
    "TARGET = 'salary_mean_net'\n"
    "y_raw  = train[TARGET].values.astype(np.float64)\n"
    "\n"
    "lv1 = train.groupby(['employer_id', 'experience_name'])[TARGET].agg(median='median', count='count').reset_index()\n"
    "lv2 = train.groupby('employer_id')[TARGET].agg(median='median', count='count').reset_index()\n"
    "lv3 = train.groupby(['professional_roles_name', 'experience_name'])[TARGET].agg(median='median', count='count').reset_index()\n"
    "lv4 = train.groupby('professional_roles_name')[TARGET].agg(median='median', count='count').reset_index()\n"
    "lv5 = train.groupby(['specializations_profarea_name', 'experience_name'])[TARGET].agg(median='median', count='count').reset_index()\n"
    "global_median = train[TARGET].median()\n"
    "\n"
    "print(f'LV1 (emp+exp): {len(lv1)}, LV2 (emp): {len(lv2)}, LV3 (role+exp): {len(lv3)}')\n"
    "print(f'LV4 (role): {len(lv4)}, Global median: {global_median:.0f}')"
))

cells.append(make_code(
    "def hierarchical_lookup(df):\n"
    "    result = df[['employer_id','experience_name','professional_roles_name','specializations_profarea_name']].copy()\n"
    "    result['lookup_pred']  = np.nan\n"
    "    result['lookup_count'] = 0\n"
    "    result['lookup_level'] = 6\n"
    "\n"
    "    m1 = result.merge(lv1[['employer_id','experience_name','median','count']], on=['employer_id','experience_name'], how='left')\n"
    "    mask1 = m1['median'].notna()\n"
    "    result.loc[mask1, 'lookup_pred']  = m1.loc[mask1, 'median'].values\n"
    "    result.loc[mask1, 'lookup_count'] = m1.loc[mask1, 'count'].values\n"
    "    result.loc[mask1, 'lookup_level'] = 1\n"
    "\n"
    "    need = result['lookup_pred'].isna()\n"
    "    m2 = result[need].merge(lv2[['employer_id','median','count']], on='employer_id', how='left')\n"
    "    mask2 = m2['median'].notna()\n"
    "    idx2 = result[need].index[mask2]\n"
    "    result.loc[idx2, 'lookup_pred']  = m2.loc[mask2, 'median'].values\n"
    "    result.loc[idx2, 'lookup_count'] = m2.loc[mask2, 'count'].values\n"
    "    result.loc[idx2, 'lookup_level'] = 2\n"
    "\n"
    "    need = result['lookup_pred'].isna()\n"
    "    m3 = result[need].merge(lv3[['professional_roles_name','experience_name','median','count']], on=['professional_roles_name','experience_name'], how='left')\n"
    "    mask3 = m3['median'].notna()\n"
    "    idx3 = result[need].index[mask3]\n"
    "    result.loc[idx3, 'lookup_pred']  = m3.loc[mask3, 'median'].values\n"
    "    result.loc[idx3, 'lookup_count'] = m3.loc[mask3, 'count'].values\n"
    "    result.loc[idx3, 'lookup_level'] = 3\n"
    "\n"
    "    need = result['lookup_pred'].isna()\n"
    "    m4 = result[need].merge(lv4[['professional_roles_name','median','count']], on='professional_roles_name', how='left')\n"
    "    mask4 = m4['median'].notna()\n"
    "    idx4 = result[need].index[mask4]\n"
    "    result.loc[idx4, 'lookup_pred']  = m4.loc[mask4, 'median'].values\n"
    "    result.loc[idx4, 'lookup_count'] = m4.loc[mask4, 'count'].values\n"
    "    result.loc[idx4, 'lookup_level'] = 4\n"
    "\n"
    "    need = result['lookup_pred'].isna()\n"
    "    m5 = result[need].merge(lv5[['specializations_profarea_name','experience_name','median','count']], on=['specializations_profarea_name','experience_name'], how='left')\n"
    "    mask5 = m5['median'].notna()\n"
    "    idx5 = result[need].index[mask5]\n"
    "    result.loc[idx5, 'lookup_pred']  = m5.loc[mask5, 'median'].values\n"
    "    result.loc[idx5, 'lookup_count'] = m5.loc[mask5, 'count'].values\n"
    "    result.loc[idx5, 'lookup_level'] = 5\n"
    "\n"
    "    still_na = result['lookup_pred'].isna()\n"
    "    result.loc[still_na, 'lookup_pred']  = global_median\n"
    "    result.loc[still_na, 'lookup_count'] = 1\n"
    "    result.loc[still_na, 'lookup_level'] = 6\n"
    "\n"
    "    return result[['lookup_pred', 'lookup_count', 'lookup_level']]\n"
    "\n"
    "\n"
    "train_lookup = hierarchical_lookup(train)\n"
    "train_mape_lookup = np.mean(np.abs((y_raw - train_lookup['lookup_pred'].values) / (y_raw + 1e-8)))\n"
    "print(f'Train lookup MAPE (in-sample): {train_mape_lookup:.4f}')\n"
    "print('Lookup level distribution (train):')\n"
    "print(train_lookup['lookup_level'].value_counts().sort_index())\n"
    "\n"
    "test_lookup = hierarchical_lookup(test)\n"
    "print('\\nLookup level distribution (test):')\n"
    "print(test_lookup['lookup_level'].value_counts().sort_index())"
))

cells.append(make_md("### 4. OOF Lookup MAPE (unbiased estimate)"))
cells.append(make_code(
    "kf = KFold(n_splits=N_SPLITS, shuffle=True, random_state=SEED)\n"
    "oof_lookup = np.zeros(len(train))\n"
    "\n"
    "for tr_idx, val_idx in kf.split(train):\n"
    "    tr_fold  = train.iloc[tr_idx]\n"
    "    val_fold = train.iloc[val_idx]\n"
    "\n"
    "    lv1_f = tr_fold.groupby(['employer_id','experience_name'])[TARGET].median()\n"
    "    lv2_f = tr_fold.groupby('employer_id')[TARGET].median()\n"
    "    lv3_f = tr_fold.groupby(['professional_roles_name','experience_name'])[TARGET].median()\n"
    "    lv4_f = tr_fold.groupby('professional_roles_name')[TARGET].median()\n"
    "    lv5_f = tr_fold.groupby(['specializations_profarea_name','experience_name'])[TARGET].median()\n"
    "    gm_f  = tr_fold[TARGET].median()\n"
    "\n"
    "    preds = np.full(len(val_fold), gm_f)\n"
    "    for i, (_, row) in enumerate(val_fold.iterrows()):\n"
    "        key1 = (row['employer_id'], row['experience_name'])\n"
    "        key2 = row['employer_id']\n"
    "        key3 = (row['professional_roles_name'], row['experience_name'])\n"
    "        key4 = row['professional_roles_name']\n"
    "        key5 = (row['specializations_profarea_name'], row['experience_name'])\n"
    "        if key1 in lv1_f.index:   preds[i] = lv1_f[key1]\n"
    "        elif key2 in lv2_f.index: preds[i] = lv2_f[key2]\n"
    "        elif key3 in lv3_f.index: preds[i] = lv3_f[key3]\n"
    "        elif key4 in lv4_f.index: preds[i] = lv4_f[key4]\n"
    "        elif key5 in lv5_f.index: preds[i] = lv5_f[key5]\n"
    "    oof_lookup[val_idx] = preds\n"
    "\n"
    "oof_lookup_mape = np.mean(np.abs((y_raw - oof_lookup) / (y_raw + 1e-8)))\n"
    "print(f'OOF Lookup MAPE (unbiased): {oof_lookup_mape:.4f}')"
))

cells.append(make_md("### 5. Feature Engineering"))
cells.append(make_code(
    "DESC_COL  = 'lemmaized_wo_stopwords_raw_description'\n"
    "TITLE_COL = 'name_clean'\n"
    "\n"
    "for df in [train, test]:\n"
    "    df[DESC_COL]  = df[DESC_COL].fillna('')\n"
    "    df[TITLE_COL] = df[TITLE_COL].fillna('')\n"
    "\n"
    "n_train = len(train)\n"
    "corpus_desc  = pd.concat([train[DESC_COL],  test[DESC_COL]],  ignore_index=True)\n"
    "corpus_title = pd.concat([train[TITLE_COL], test[TITLE_COL]], ignore_index=True)\n"
    "\n"
    "tfidf_desc  = TfidfVectorizer(max_features=6000, sublinear_tf=True, min_df=3, ngram_range=(1,2), dtype=np.float32)\n"
    "tfidf_title = TfidfVectorizer(max_features=3000, sublinear_tf=True, min_df=2, ngram_range=(1,2), dtype=np.float32)\n"
    "svd_desc    = TruncatedSVD(n_components=100, random_state=SEED)\n"
    "svd_title   = TruncatedSVD(n_components=40,  random_state=SEED)\n"
    "\n"
    "mat_desc  = svd_desc.fit_transform(tfidf_desc.fit_transform(corpus_desc)).astype(np.float32)\n"
    "mat_title = svd_title.fit_transform(tfidf_title.fit_transform(corpus_title)).astype(np.float32)\n"
    "\n"
    "SVD_TRAIN = pd.DataFrame(\n"
    "    np.hstack([mat_desc[:n_train], mat_title[:n_train]]),\n"
    "    columns=[f'desc_svd_{i}' for i in range(100)] + [f'title_svd_{i}' for i in range(40)]\n"
    ")\n"
    "SVD_TEST = pd.DataFrame(\n"
    "    np.hstack([mat_desc[n_train:], mat_title[n_train:]]),\n"
    "    columns=SVD_TRAIN.columns\n"
    ")\n"
    "print(f'SVD ready: {SVD_TRAIN.shape}')"
))

cells.append(make_code(
    "EXPERIENCE_ORDER = ['\\u041d\\u0435\\u0442 \\u043e\\u043f\\u044b\\u0442\\u0430', '\\u041e\\u0442 1 \\u0433\\u043e\\u0434\\u0430 \\u0434\\u043e 3 \\u043b\\u0435\\u0442', '\\u041e\\u0442 3 \\u0434\\u043e 6 \\u043b\\u0435\\u0442', '\\u0411\\u043e\\u043b\\u0435\\u0435 6 \\u043b\\u0435\\u0442']\n"
    "DROP_COLS = [\n"
    "    'id', 'salary_mean_net', 'raw_description', 'raw_branded_description',\n"
    "    'lemmaized_wo_stopwords_raw_branded_description', 'lemmaized_wo_stopwords_raw_description',\n"
    "    'name', 'name_clean', 'unified_address_country',\n"
    "]\n"
    "LOW_CARD_COLS = ['schedule_name', 'employment_name', 'is_branded_description',\n"
    "                 'if_foreign_language', 'accept_handicapped', 'accept_kids']\n"
    "TE_COLS = ['employer_id', 'employer_name', 'professional_roles_name',\n"
    "           'specializations_profarea_name', 'employer_industries',\n"
    "           'unified_address_city', 'unified_address_state', 'unified_address_region']\n"
    "\n"
    "exp_map = {v: i for i, v in enumerate(EXPERIENCE_ORDER)}\n"
    "for df in [train, test]:\n"
    "    df['experience_ord']  = df['experience_name'].map(exp_map).fillna(-1).astype(np.int8)\n"
    "    df['desc_word_count'] = df[DESC_COL].str.split().str.len().fillna(0).astype(np.int16)\n"
    "    df['has_skills']      = (df['key_skills_name'].fillna('[]') != '[]').astype(np.int8)\n"
    "    df['has_languages']   = (df['languages_name'].fillna('[]') != '[]').astype(np.int8)\n"
    "    df['skills_count']    = df['key_skills_name'].fillna('[]').str.count(',').astype(np.int16)\n"
    "    city = df['unified_address_city'].fillna('').str.lower()\n"
    "    df['is_moscow'] = city.str.contains('\\u043c\\u043e\\u0441\\u043a\\u0432\\u0430').astype(np.int8)\n"
    "    df['is_spb']    = city.str.contains('\\u0441\\u0430\\u043d\\u043a\\u0442').astype(np.int8)\n"
    "    for col in TE_COLS:\n"
    "        if col in df.columns:\n"
    "            df[col] = df[col].fillna('__NA__').astype(str)\n"
    "\n"
    "oe = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1, dtype=np.float32)\n"
    "train[LOW_CARD_COLS] = oe.fit_transform(train[LOW_CARD_COLS].astype(str))\n"
    "test[LOW_CARD_COLS]  = oe.transform(test[LOW_CARD_COLS].astype(str))\n"
    "\n"
    "train['lookup_pred']  = oof_lookup\n"
    "train['lookup_level'] = train_lookup['lookup_level'].values\n"
    "test['lookup_pred']   = test_lookup['lookup_pred'].values\n"
    "test['lookup_level']  = test_lookup['lookup_level'].values\n"
    "\n"
    "y  = np.log1p(y_raw).astype(np.float32)\n"
    "gm = float(np.mean(y))\n"
    "\n"
    "base_cols = [\n"
    "    c for c in train.columns\n"
    "    if c not in DROP_COLS + TE_COLS + ['experience_name', 'key_skills_name', 'languages_name']\n"
    "    and train[c].dtype != object\n"
    "]\n"
    "\n"
    "X_base_tr = train[base_cols].reset_index(drop=True)\n"
    "X_base_te = test[[c for c in base_cols if c in test.columns]].reset_index(drop=True)\n"
    "X_base_te = X_base_te.reindex(columns=X_base_tr.columns)\n"
    "print(f'Base features: {X_base_tr.shape[1]}')"
))

cells.append(make_code(
    "def smoothed_te(col_tr, col_val, col_te, y_tr, global_mean, k=STE_K):\n"
    "    stats = pd.DataFrame({'y': y_tr, 'cat': col_tr.values}).groupby('cat')['y'].agg(['mean','count'])\n"
    "    stats['smooth'] = (stats['count'] * stats['mean'] + k * global_mean) / (stats['count'] + k)\n"
    "    te_map = stats['smooth']\n"
    "    return (\n"
    "        col_tr.map(te_map).fillna(global_mean),\n"
    "        col_val.map(te_map).fillna(global_mean),\n"
    "        col_te.map(te_map).fillna(global_mean),\n"
    "    )\n"
    "\n"
    "\n"
    "def build_fold(tr_idx, val_idx):\n"
    "    te_tr_l, te_val_l, te_te_l = [], [], []\n"
    "    for col in TE_COLS:\n"
    "        s_tr, s_val, s_te = smoothed_te(\n"
    "            train[col].iloc[tr_idx].reset_index(drop=True),\n"
    "            train[col].iloc[val_idx].reset_index(drop=True),\n"
    "            test[col].reset_index(drop=True),\n"
    "            y[tr_idx], gm,\n"
    "        )\n"
    "        te_tr_l.append(s_tr.rename(f'te_{col}'))\n"
    "        te_val_l.append(s_val.rename(f'te_{col}'))\n"
    "        te_te_l.append(s_te.rename(f'te_{col}'))\n"
    "\n"
    "    te_tr  = pd.concat(te_tr_l,  axis=1)\n"
    "    te_val = pd.concat(te_val_l, axis=1)\n"
    "    te_te  = pd.concat(te_te_l,  axis=1)\n"
    "\n"
    "    def assemble(base, svd, te):\n"
    "        out = pd.concat([base, svd, te], axis=1)\n"
    "        out['exp_x_role_te'] = out['experience_ord'].astype(float) * out['te_professional_roles_name']\n"
    "        out['moscow_x_exp']  = out['is_moscow'].astype(float) * out['experience_ord'].astype(float)\n"
    "        return out\n"
    "\n"
    "    return (\n"
    "        assemble(X_base_tr.iloc[tr_idx].reset_index(drop=True), SVD_TRAIN.iloc[tr_idx].reset_index(drop=True), te_tr),\n"
    "        assemble(X_base_tr.iloc[val_idx].reset_index(drop=True), SVD_TRAIN.iloc[val_idx].reset_index(drop=True), te_val),\n"
    "        assemble(X_base_te.reset_index(drop=True), SVD_TEST.reset_index(drop=True), te_te),\n"
    "    )\n"
    "\n"
    "print('Build fold helper ready.')"
))

cells.append(make_md("### 6. LightGBM OOF"))
cells.append(make_code(
    "lgb_params = {\n"
    "    'objective': 'regression', 'metric': 'rmse',\n"
    "    'n_estimators': 8000, 'learning_rate': 0.02,\n"
    "    'num_leaves': 255, 'min_child_samples': 15,\n"
    "    'feature_fraction': 0.6, 'bagging_fraction': 0.8, 'bagging_freq': 5,\n"
    "    'reg_alpha': 0.05, 'reg_lambda': 0.1,\n"
    "    'random_state': SEED, 'n_jobs': -1, 'verbose': -1,\n"
    "}\n"
    "\n"
    "oof_lgb  = np.zeros(len(train), dtype=np.float64)\n"
    "pred_lgb = np.zeros(len(test),  dtype=np.float64)\n"
    "\n"
    "for fold, (tr_idx, val_idx) in enumerate(kf.split(X_base_tr)):\n"
    "    X_tr, X_val, X_te = build_fold(tr_idx, val_idx)\n"
    "    m = lgb.LGBMRegressor(**lgb_params)\n"
    "    m.fit(X_tr, y[tr_idx], eval_set=[(X_val, y[val_idx])],\n"
    "          callbacks=[lgb.early_stopping(200, verbose=False), lgb.log_evaluation(1000)])\n"
    "    vp = np.expm1(m.predict(X_val))\n"
    "    oof_lgb[val_idx] = vp\n"
    "    pred_lgb += np.expm1(m.predict(X_te)) / N_SPLITS\n"
    "    mape = np.mean(np.abs((y_raw[val_idx] - vp) / (y_raw[val_idx] + 1e-8)))\n"
    "    print(f'Fold {fold+1} | LGB MAPE: {mape:.4f} | iter: {m.best_iteration_}')\n"
    "\n"
    "lgb_oof_mape = np.mean(np.abs((y_raw - oof_lgb) / (y_raw + 1e-8)))\n"
    "print(f'\\nLightGBM OOF MAPE: {lgb_oof_mape:.4f}')"
))

cells.append(make_md("### 7. XGBoost OOF"))
cells.append(make_code(
    "xgb_params = {\n"
    "    'objective': 'reg:squarederror',\n"
    "    'eval_metric': 'rmse',\n"
    "    'n_estimators': 8000,\n"
    "    'learning_rate': 0.02,\n"
    "    'max_depth': 7,\n"
    "    'min_child_weight': 10,\n"
    "    'subsample': 0.8,\n"
    "    'colsample_bytree': 0.6,\n"
    "    'reg_alpha': 0.05,\n"
    "    'reg_lambda': 0.1,\n"
    "    'random_state': SEED,\n"
    "    'n_jobs': -1,\n"
    "    'tree_method': 'hist',\n"
    "    'early_stopping_rounds': 200,\n"
    "    'verbosity': 0,\n"
    "}\n"
    "\n"
    "oof_xgb  = np.zeros(len(train), dtype=np.float64)\n"
    "pred_xgb = np.zeros(len(test),  dtype=np.float64)\n"
    "\n"
    "for fold, (tr_idx, val_idx) in enumerate(kf.split(X_base_tr)):\n"
    "    X_tr, X_val, X_te = build_fold(tr_idx, val_idx)\n"
    "    m = xgb.XGBRegressor(**xgb_params)\n"
    "    m.fit(X_tr, y[tr_idx], eval_set=[(X_val, y[val_idx])], verbose=False)\n"
    "    vp = np.expm1(m.predict(X_val))\n"
    "    oof_xgb[val_idx] = vp\n"
    "    pred_xgb += np.expm1(m.predict(X_te)) / N_SPLITS\n"
    "    mape = np.mean(np.abs((y_raw[val_idx] - vp) / (y_raw[val_idx] + 1e-8)))\n"
    "    print(f'Fold {fold+1} | XGB MAPE: {mape:.4f} | iter: {m.best_iteration}')\n"
    "\n"
    "xgb_oof_mape = np.mean(np.abs((y_raw - oof_xgb) / (y_raw + 1e-8)))\n"
    "print(f'\\nXGBoost OOF MAPE: {xgb_oof_mape:.4f}')"
))

cells.append(make_md("### 8. Ensemble Blending"))
cells.append(make_code(
    "# ML ensemble: simple average of LGB and XGB\n"
    "oof_ml   = 0.5 * oof_lgb  + 0.5 * oof_xgb\n"
    "pred_ml  = 0.5 * pred_lgb + 0.5 * pred_xgb\n"
    "\n"
    "ml_oof_mape = np.mean(np.abs((y_raw - oof_ml) / (y_raw + 1e-8)))\n"
    "print(f'ML ensemble OOF MAPE: {ml_oof_mape:.4f}')\n"
    "print(f'Lookup OOF MAPE:       {oof_lookup_mape:.4f}')\n"
    "\n"
    "# Lookup alpha by level: higher level = more confident lookup\n"
    "ALPHA_MAP = {1: 0.80, 2: 0.60, 3: 0.30, 4: 0.15, 5: 0.10, 6: 0.05}\n"
    "\n"
    "# OOF blend\n"
    "train_levels = train_lookup['lookup_level'].values\n"
    "alpha_oof = np.array([ALPHA_MAP[lv] for lv in train_levels])\n"
    "oof_blend = alpha_oof * oof_lookup + (1 - alpha_oof) * oof_ml\n"
    "blend_oof_mape = np.mean(np.abs((y_raw - oof_blend) / (y_raw + 1e-8)))\n"
    "print(f'\\nBlend OOF MAPE: {blend_oof_mape:.4f}')\n"
    "\n"
    "# Per-level breakdown\n"
    "print('\\nPer-level MAPE breakdown:')\n"
    "for lv in sorted(ALPHA_MAP.keys()):\n"
    "    mask = train_levels == lv\n"
    "    if mask.sum()
